# Generated by Django 4.2 on 2023-05-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=250, verbose_name='Фото')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('raiting', models.CharField(max_length=250, verbose_name='Рейтинг')),
                ('tech', models.BooleanField(verbose_name='Tech')),
                ('Community', models.BooleanField(verbose_name='Community')),
                ('status', models.CharField(max_length=250, verbose_name='Статус')),
                ('dates', models.CharField(max_length=250, verbose_name='Дата')),
                ('rewards', models.CharField(max_length=250, verbose_name='Награды')),
                ('lock', models.CharField(max_length=250, verbose_name='Закрытие')),
                ('hardware', models.IntegerField(verbose_name='Оборудование')),
                ('Complexity', models.IntegerField(verbose_name='Сложность')),
                ('cpu', models.CharField(max_length=250, verbose_name='Процессор')),
                ('ram', models.CharField(max_length=250, verbose_name='Оперативная память')),
                ('os', models.CharField(max_length=250, verbose_name='Операционная система')),
                ('storage', models.CharField(max_length=250, verbose_name='Память')),
                ('network', models.CharField(max_length=250, verbose_name='Скорость интернета')),
                ('note', models.CharField(max_length=250, verbose_name='Примечание')),
                ('template_name', models.CharField(max_length=250, verbose_name='Название шаблона гайда')),
                ('start', models.CharField(max_length=250, verbose_name='Дата старта проекта')),
            ],
        ),
    ]
