# Generated by Django 4.1.5 on 2023-06-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_node_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='template_world',
            field=models.CharField(default='nothing', max_length=250, verbose_name='Имя инфографиков'),
        ),
        migrations.AddField(
            model_name='node',
            name='urldef',
            field=models.CharField(default='nothing', max_length=250, verbose_name='Сылка на оф. гайд'),
        ),
    ]
