# Generated by Django 4.2 on 2023-06-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_node_template_world_node_urldef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название ноды')),
                ('field1', models.IntegerField(verbose_name='December')),
                ('field2', models.IntegerField(verbose_name='January')),
                ('field3', models.IntegerField(verbose_name='February')),
                ('field4', models.IntegerField(verbose_name='March')),
                ('field5', models.IntegerField(verbose_name='April')),
                ('field6', models.IntegerField(verbose_name='May')),
            ],
        ),
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название ноды')),
                ('field1', models.IntegerField(verbose_name='South Korea')),
                ('field2', models.IntegerField(verbose_name='Germany')),
                ('field3', models.IntegerField(verbose_name='United States')),
                ('field4', models.IntegerField(verbose_name='Hong Kong')),
                ('field5', models.IntegerField(verbose_name='Singapore')),
                ('field6', models.IntegerField(verbose_name='Russia')),
                ('field7', models.IntegerField(verbose_name='Netherlands')),
                ('field8', models.IntegerField(verbose_name='Finland')),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название ноды')),
                ('field1', models.IntegerField(verbose_name='Korea Talecom')),
                ('field2', models.IntegerField(verbose_name='KORNET')),
                ('field3', models.IntegerField(verbose_name='(ju)haepimeoniaissi')),
                ('field4', models.IntegerField(verbose_name='Contabo')),
                ('field5', models.IntegerField(verbose_name='Kornet')),
                ('field6', models.IntegerField(verbose_name='Digital Ocean')),
                ('field7', models.IntegerField(verbose_name='Alibaba.com Singapore E-Co')),
                ('field8', models.IntegerField(verbose_name='Hetzner')),
            ],
        ),
    ]
